AWSTemplateFormatVersion: 2010-09-09
Description: >-
  This stack creates and configures two file servers. These file servers will have a second volume, 
  created to isolate files for file shares (and to ease file paths during configuration), a DFS 
  namespace, DFS replication, and possibly FSRM for file screens.
Parameters:
  DomainDNSName:
    Type: String
    Description: >-
      This domain name should be the domain name used in the ADStack.
      The domain name as it would be entered into a browser. (Ex. "example.com")
    AllowedPattern: '[a-zA-Z0-9\-]+\..+'
    MaxLength: '25'
    MinLength: '3'
  DomainNetBIOSName:
    Type: String
    Description: >-
      This NetBIOS name should be the same as the name used in ADStack.
      The NetBIOS name of the domain, typically the same as the domain DNS name, but with the 
      root domain removed. (Ex. "EXAMPLE")
    AllowedPattern: '[a-zA-Z0-9\-]+'
    MaxLength: '15'
    MinLength: '1'
  DomainAdminUser:
    Type: String
    Description: >-
      This username should be for the same user created in ADStack.
      The user name of a user to be added and given Domain Admin privileges.
      This user is separate from the default Administrator account.
    AllowedPattern: '[a-zA-Z0-9]*'
    MaxLength: '25'
    MinLength: '3'
  DomainAdminPassword:
    Type: String
    Description: >-
      This password should be for the same user created in ADStack.
      The account password for the domain admin user.
  FSInstanceType:
    Type: String
    Description: 'The instance type for the File Servers. Default: t2.micro'
    AllowedValues:
      - t2.micro
      - t2.small
      - t2.medium
      - t2.large
      - t2.xlarge
      - t2.2xlarge
      - m5.large
      - m5.xlarge
      - m5.2xlarge
      - m5.4xlarge
    Default: t2.micro
  FSImage:
    Type: String
    Description: 'The AMI ID to be used when creating file servers.'
    Default: 'ami-05446e60'
  FSVolumeSize:
    Type: Integer
    Description: 'The size of volumes to add to file server instances for file shares.'
  KeyPair:
    Type: 'AWS::EC2::KeyPair::KeyName'
    Description: >-
      The name of the key pair used to connect to instances. Without this, 
      instances are inaccessible to remote administration.
  FS1PrivIP:
    Type: String
    Description: 'The private IP to be used for FS1.'
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
    Default: 10.0.2.20
  FS1NetBIOSName:
    Type: String
    Description: 'The NetBIOS name for the first file server.'
    AllowedPattern: '[a-zA-Z0-9\-]+'
    Default: FS1
    MaxLength: '15'
    MinLength: '1'
  FS2PrivIP:
    Type: String
    Description: 'The private IP to be used for FS2.'
    AllowedPattern: >-
      ^(([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])\.){3}([0-9]|[1-9][0-9]|1[0-9]{2}|2[0-4][0-9]|25[0-5])$
    Default: 10.0.4.20
  FS2NetBIOSName:
    Type: String
    Description: 'The NetBIOS name for the second file server.'
    AllowedPattern: '[a-zA-Z0-9\-]+'
    Default: FS2
    MaxLength: '15'
    MinLength: '1'
Resources:
  FS1:
    Type: 'AWS::EC2::Instance'
    ImageId: !Ref FSImage
    InstanceType: !Ref FSInstanceType
    KeyName: !Ref KeyPair
    PrivateIpAddress: !Ref FS1PrivIp
    SecurityGroupIds:
      - Fn::ImportValue:
        !Sub '${ADStackName}-DomainMemberSG
      - !Ref FS1SecurityGroup
    SubnetId: 
      Fn::ImportValue:
        !Sub '${NetworkStackName}-PrivSub2Id'
    Tags:
      - Key: 'Name'
        Value: 'FS1'
    UserData:
      Fn::Join:
          - ''
          - - |
              <script>
            - 'cfn-init.exe -v -c config -s '
            - !Ref 'AWS::StackId'
            - ' -r FS1 --region '
            - !Ref 'AWS::Region'
            - |+
            - |
              </script>
    Volumes:
      - VolumeId: !Ref FS1Volume
        Device: 'xvdf'
    AdditionalInfo: 
  FS1Volume:
    Type: 'AWS::EC2::Volume'
    AvailabilityZone: !Ref PrimaryAZ
    Size: !Ref FSVolumeSize
    Tags:
      - Key: 'Name'
        Value: 'FS1-Volume2'
    VolumeType: 'gp2'
  FS2Volume:
    Type: 'AWS::EC2::Volume'
    AvailabilityZone: !Ref SecondaryAZ
    Size: !Ref FSVolumeSize
    Tags:
      - Key: 'Name'
        Value: 'FS2-Volume2'
    VolumeType: 'gp2'